package config

const (
	// 最大忍受时间发生回拨时常 单位(毫秒)
	maxEndureMs = 5
	// 最大系统时间误差 单位(毫秒)
	maxSysTimeErrorMs        = 100
	WORKER_GRPC_HOST_DEFAULT = "127.0.0.1"
	WORKER_GRPC_PORT_DEFAULT = "3212"
	WORKER_HTTP_HOST_DEFAULT = "127.0.0.1"
	WORKER_HTTP_PORT_DEFAULT = "3213"
	CONF_FILE_ENV_KEY        = "YC_SNOWFLAKE_CONF"
	WORKER_ID_ENV_KEY        = "YC_SNOWFLAKE_WORKER_ID"
	WORKER_GRPC_HOST_ENV_KEY = "YC_SNOWFLAKE_WORKER_RPC_HOST"
	WORKER_GRPC_PORT_ENV_KEY = "YC_SNOWFLAKE_WORKER_RPC_PORT"
	WORKER_HTTP_HOST_ENV_KEY = "YC_SNOWFLAKE_WORKER_HTTP_HOST"
	WORKER_HTTP_PORT_ENV_KEY = "YC_SNOWFLAKE_WORKER_HTTP_PORT"
	ETCD_CLUSTER_ENV_KEY     = "YC_SNOWFLAKE_CLUSTER"
	CA_FILE_ENV_KEY          = "ETCD_TRUSTED_CA_FILE"
	CLIENT_CERT_FILE_ENV_KEY = "ETCD_CERT_FILE"
	CLIENT_KEY_FILE_ENV_KEY  = "ETCD_KEY_FILE"
)