// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verify.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_verify_cf706616b4722918, []int{0}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type SysTimestamp struct {
	Timestamp            uint64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysTimestamp) Reset()         { *m = SysTimestamp{} }
func (m *SysTimestamp) String() string { return proto.CompactTextString(m) }
func (*SysTimestamp) ProtoMessage()    {}
func (*SysTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_verify_cf706616b4722918, []int{1}
}
func (m *SysTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysTimestamp.Unmarshal(m, b)
}
func (m *SysTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysTimestamp.Marshal(b, m, deterministic)
}
func (dst *SysTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysTimestamp.Merge(dst, src)
}
func (m *SysTimestamp) XXX_Size() int {
	return xxx_messageInfo_SysTimestamp.Size(m)
}
func (m *SysTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_SysTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_SysTimestamp proto.InternalMessageInfo

func (m *SysTimestamp) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type RequestUUID struct {
	WorkerId             uint64   `protobuf:"varint,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUUID) Reset()         { *m = RequestUUID{} }
func (m *RequestUUID) String() string { return proto.CompactTextString(m) }
func (*RequestUUID) ProtoMessage()    {}
func (*RequestUUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_verify_cf706616b4722918, []int{2}
}
func (m *RequestUUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUUID.Unmarshal(m, b)
}
func (m *RequestUUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUUID.Marshal(b, m, deterministic)
}
func (dst *RequestUUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUUID.Merge(dst, src)
}
func (m *RequestUUID) XXX_Size() int {
	return xxx_messageInfo_RequestUUID.Size(m)
}
func (m *RequestUUID) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUUID.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUUID proto.InternalMessageInfo

func (m *RequestUUID) GetWorkerId() uint64 {
	if m != nil {
		return m.WorkerId
	}
	return 0
}

type ResponseUUID struct {
	Uuid                 uint64   `protobuf:"varint,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUUID) Reset()         { *m = ResponseUUID{} }
func (m *ResponseUUID) String() string { return proto.CompactTextString(m) }
func (*ResponseUUID) ProtoMessage()    {}
func (*ResponseUUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_verify_cf706616b4722918, []int{3}
}
func (m *ResponseUUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUUID.Unmarshal(m, b)
}
func (m *ResponseUUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUUID.Marshal(b, m, deterministic)
}
func (dst *ResponseUUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUUID.Merge(dst, src)
}
func (m *ResponseUUID) XXX_Size() int {
	return xxx_messageInfo_ResponseUUID.Size(m)
}
func (m *ResponseUUID) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUUID.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUUID proto.InternalMessageInfo

func (m *ResponseUUID) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func init() {
	proto.RegisterType((*Void)(nil), "Void")
	proto.RegisterType((*SysTimestamp)(nil), "SysTimestamp")
	proto.RegisterType((*RequestUUID)(nil), "RequestUUID")
	proto.RegisterType((*ResponseUUID)(nil), "ResponseUUID")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	GetSysTimestamp(ctx context.Context, in *Void, opts ...grpc.CallOption) (*SysTimestamp, error)
	GetUUID(ctx context.Context, in *RequestUUID, opts ...grpc.CallOption) (*ResponseUUID, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetSysTimestamp(ctx context.Context, in *Void, opts ...grpc.CallOption) (*SysTimestamp, error) {
	out := new(SysTimestamp)
	err := c.cc.Invoke(ctx, "/TaskService/GetSysTimestamp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetUUID(ctx context.Context, in *RequestUUID, opts ...grpc.CallOption) (*ResponseUUID, error) {
	out := new(ResponseUUID)
	err := c.cc.Invoke(ctx, "/TaskService/GetUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	GetSysTimestamp(context.Context, *Void) (*SysTimestamp, error)
	GetUUID(context.Context, *RequestUUID) (*ResponseUUID, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_GetSysTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetSysTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/GetSysTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetSysTimestamp(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TaskService/GetUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetUUID(ctx, req.(*RequestUUID))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSysTimestamp",
			Handler:    _TaskService_GetSysTimestamp_Handler,
		},
		{
			MethodName: "GetUUID",
			Handler:    _TaskService_GetUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verify.proto",
}

func init() { proto.RegisterFile("verify.proto", fileDescriptor_verify_cf706616b4722918) }

var fileDescriptor_verify_cf706616b4722918 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4b, 0x2d, 0xca,
	0x4c, 0xab, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x62, 0xe3, 0x62, 0x09, 0xcb, 0xcf, 0x4c,
	0x51, 0xd2, 0xe1, 0xe2, 0x09, 0xae, 0x2c, 0x0e, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d,
	0x10, 0x92, 0xe1, 0xe2, 0x2c, 0x81, 0x71, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0x10, 0x02,
	0x4a, 0x9a, 0x5c, 0xdc, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0xa1, 0xa1, 0x9e, 0x2e, 0x42,
	0x52, 0x5c, 0x1c, 0xe5, 0xf9, 0x45, 0xd9, 0xa9, 0x45, 0x9e, 0x29, 0x50, 0xb5, 0x70, 0xbe, 0x92,
	0x12, 0x17, 0x4f, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x58, 0xad, 0x10, 0x17, 0x4b,
	0x69, 0x69, 0x66, 0x8a, 0x04, 0x13, 0x58, 0x1d, 0x98, 0x6d, 0x14, 0xc7, 0xc5, 0x1d, 0x92, 0x58,
	0x9c, 0x1d, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xa4, 0xce, 0xc5, 0xef, 0x9e, 0x5a, 0x82,
	0xe2, 0x1c, 0x56, 0x3d, 0x90, 0x2b, 0xa5, 0x78, 0xf5, 0x50, 0x44, 0xd5, 0xb8, 0xd8, 0xdd, 0x53,
	0x21, 0x4e, 0xe0, 0xd1, 0x43, 0x72, 0x90, 0x14, 0xaf, 0x1e, 0xb2, 0x9d, 0x49, 0x6c, 0x60, 0xbf,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x1d, 0x59, 0x49, 0xfb, 0x00, 0x00, 0x00,
}
